"""
Document Tools - Save vacation plans to Word documents
"""
import os
from datetime import datetime
from typing import Dict, Any


def save_vacation_plan(
    destination: str,
    content: str,
    output_dir: str = "outputs"
) -> Dict[str, Any]:
    """
    Save vacation plan to a Word document (.docx).
    
    Args:
        destination: Destination name (used in filename)
        content: The vacation plan content (markdown formatted)
        output_dir: Directory to save the file (default: outputs)
    
    Returns:
        Dictionary with file path and status
    """
    try:
        from docx import Document
        from docx.shared import Inches, Pt, RGBColor
        from docx.enum.text import WD_ALIGN_PARAGRAPH
        
        # Create output directory if it doesn't exist
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)
        
        # Create filename with destination and timestamp
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_destination = destination.replace(" ", "_").replace(",", "")
        filename = f"vacation_plan_{safe_destination}_{timestamp}.docx"
        filepath = os.path.join(output_dir, filename)
        
        # Create Word document
        doc = Document()
        
        # Add title
        title = doc.add_heading('Vacation Plan Summary', 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        # Parse and add content
        lines = content.split('\n')
        for line in lines:
            line = line.strip()
            
            # Skip empty lines
            if not line:
                continue
                
            # Handle headers
            if line.startswith('# '):
                doc.add_heading(line[2:], level=1)
            elif line.startswith('## '):
                doc.add_heading(line[3:], level=2)
            elif line.startswith('### '):
                doc.add_heading(line[4:], level=3)
            
            # Handle bullet points
            elif line.startswith('- ') or line.startswith('* '):
                doc.add_paragraph(line[2:], style='List Bullet')
            
            # Handle numbered lists
            elif line[0].isdigit() and line[1:3] in ['. ', ') ']:
                doc.add_paragraph(line[3:], style='List Number')
            
            # Handle bold markers
            elif line.startswith('**') and line.endswith('**'):
                p = doc.add_paragraph()
                p.add_run(line[2:-2]).bold = True
            
            # Regular paragraphs
            else:
                # Skip markdown code fences
                if line.startswith('```'):
                    continue
                doc.add_paragraph(line)
        
        # Add footer
        section = doc.sections[0]
        footer = section.footer
        footer_para = footer.paragraphs[0]
        footer_para.text = f"Generated by AI Vacation Planner on {datetime.now().strftime('%Y-%m-%d %H:%M')}"
        footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        # Save the document
        doc.save(filepath)

        # Generate download URL (works with ADK web server on port 8080)
        download_url = f"http://localhost:9000/download/{filename}"

        return {
            "status": "success",
            "filepath": filepath,
            "filename": filename,
            "download_url": download_url,
            "message": f"""✅ Vacation plan saved successfully!

**Download Your Vacation Plan:**
🔗 **Direct Download Link:** {download_url}

**File Details:**
- Filename: {filename}
- Location: {os.path.abspath(filepath)}
- Format: Microsoft Word (.docx)

**How to Download:**
1. Click the link above, or
2. Copy and paste this URL in your browser: {download_url}

Your vacation plan is ready to download!"""
        }
    
    except ImportError:
        return {
            "status": "error",
            "error": "python-docx library not installed",
            "message": "⚠️ Please install python-docx: pip install python-docx"
        }
    
    except Exception as e:
        return {
            "status": "error",
            "error": str(e),
            "message": f"❌ Failed to save vacation plan: {str(e)}"
        }
