"""
Main entry point for AI-Powered Vacation Planner
Basic implementation for Nov 25th submission
"""

import os
import asyncio
from dotenv import load_dotenv
from loguru import logger
from agents.orchestrator import OrchestratorAgent

# Configure logging
logger.add(
    "logs/vacation_planner_{time}.log",
    rotation="1 day",
    retention="7 days",
    level="INFO"
)

# Load environment variables
load_dotenv()


async def main():
    """Main application entry point"""

    print("=" * 70)
    print("🌍 AI-POWERED VACATION PLANNER")
    print("=" * 70)
    print()

    # Check environment variables
    if not os.getenv('GOOGLE_API_KEY'):
        print("❌ Error: GOOGLE_API_KEY not set in environment")
        print("   Please copy .env.example to .env and add your API key")
        return

    # Sample vacation request
    user_request = """
    I want to plan a vacation to Paris, France.
    Travel dates: June 15-25, 2025
    Origin: New York, USA
    Travelers: 2 adults
    Budget: Moderate ($4000-5000)
    Interests: Museums, French cuisine, architecture, wine tasting
    """

    print("📝 VACATION REQUEST")
    print("-" * 70)
    print(user_request.strip())
    print()

    # Initialize orchestrator
    logger.info("Initializing Orchestrator Agent")
    orchestrator = OrchestratorAgent()

    print("🤖 Processing your vacation request...")
    print()

    try:
        # Generate vacation plan
        result = await orchestrator.plan_vacation(user_request)

        # Display results
        print("=" * 70)
        print("✅ VACATION PLAN GENERATED")
        print("=" * 70)
        print()
        print(f"📋 Session ID: {result['session_id']}")
        print(f"🌍 Destination: {result.get('destination', 'N/A')}")
        print(f"✅ Status: {result['status']}")
        print()

        if 'plan' in result and 'itinerary' in result['plan']:
            print("=" * 70)
            print("📖 YOUR COMPLETE VACATION ITINERARY")
            print("=" * 70)
            print()
            print(result['plan']['itinerary'])
            print()
            print("=" * 70)
            print(f"🤖 Generated by: {result['plan'].get('model', 'AI')}")
            print(f"⏰ Generated at: {result['plan'].get('generated_at', 'N/A')}")
            print("=" * 70)
        else:
            print("⚠️  No itinerary generated")

        print()
        print("✨ Vacation planning completed successfully!")
        print()

    except Exception as e:
        logger.error(f"Error in main: {e}")
        print(f"❌ Error: {e}")
        print()


if __name__ == "__main__":
    # Create logs directory
    os.makedirs("logs", exist_ok=True)

    # Run main
    asyncio.run(main())
